### ISSUE TITLE
404 trying to get to https://fly.io/docs/getting-started/rails

### ISSUE THREAD

**Issue by mathewdbutton** [fly-apps/hello-rails#1]
I realise this repo is supppppper fresh but thought I'd mention that the getting-started rails link is returning a 404.

**Comment by cabello** [comment]
Ditto, very few mentions to Rails now on the official docs, Ruby instructions are here: https://fly.io/docs/getting-started/ruby/

**Comment by mathewdbutton** [comment]
Seems as though it's working now
https://fly.io/docs/getting-started/rails/
